apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: hb69nxdwg-nodejs 
  janus-idp.io/tekton: hb69nxdwg-nodejs
  backstage.io/kubernetes-id: hb69nxdwg-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hb69nxdwg-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml