apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hb69nxdwg-nodejs
  janus-idp.io/tekton: hb69nxdwg-nodejs
  backstage.io/kubernetes-id: hb69nxdwg-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hb69nxdwg-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
